name: pulsar
description: "Pulsar：以动态星海呈现训练计划与健身记录的 Flutter Android 应用。"
publish_to: 'none'
version: 1.11.1+15

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  file_picker: ^10.3.8
  path: ^1.9.1
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  image_path: "assets/icon.png"
  min_sdk_android: 24

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
